### ISSUE TITLE
Link para grupo Telegram quebrado

### ISSUE THREAD

**Issue by maykonchagas** [mozillabrasil/mozillabrasil.org.br#12]
Ao acessar o site na sessão participe: https://mozillabrasil.org.br/participe/ e seguir o link para entrar no grupo do Telegram https://telegram.me/joinchat/ASpmewcYA-xPegW2kTecxg aparece a mensagem que grupo não existe ou link está incorreto

**Comment by halcance** [comment]
Muito bom @mchagas   ❤️  também estou me deparando com este problema, vendo aqui no telegram, seria viável modificar para  **https://telegram.me/sumobrasil**  nos meus teste funcionaram perfeitamente.

Aguardo retorno.

**Comment by halcance** [comment]
Pull request aberto https://github.com/mozillabrasil/mozillabrasil.org.br/pull/13

**Comment by maykonchagas** [comment]
@alipseight issue resolvido! entrei pelo link novo e funcionou perfeitamente. Ah, e acho que tu referenciou o @mAraldi ao invés de mim? ,D

**Comment by halcance** [comment]
Hahaha erros aparte.
